# Generated by Django 4.0.4 on 2022-05-08 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_on', models.DateTimeField(verbose_name='received on')),
                ('downloaded_on', models.DateTimeField(verbose_name='downloaded on')),
                ('worksheet', models.FileField(upload_to='forecast', verbose_name='worksheet')),
            ],
            options={
                'verbose_name': 'forecast',
                'verbose_name_plural': 'forecast',
                'db_table': 'forecast',
            },
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_on', models.DateTimeField(verbose_name='received on')),
                ('downloaded_on', models.DateTimeField(verbose_name='downloaded on')),
                ('worksheet', models.FileField(upload_to='performance', verbose_name='worksheet')),
            ],
            options={
                'verbose_name': 'performance',
                'verbose_name_plural': 'performance',
                'db_table': 'performance',
            },
        ),
        migrations.CreateModel(
            name='PerformanceRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='start time')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='end time')),
                ('player', models.CharField(max_length=32, verbose_name='player')),
                ('metrics', models.CharField(blank=True, max_length=32, null=True, verbose_name='metrics')),
                ('abandoned_over_14', models.IntegerField(default=0, verbose_name='abandoned over 14')),
                ('responses', models.IntegerField(default=0, verbose_name='responses')),
                ('short_calls', models.IntegerField(default=0, verbose_name='short calls')),
                ('login_time', models.IntegerField(default=0, verbose_name='login time')),
                ('login_time_nt', models.IntegerField(default=0, verbose_name='login time nt')),
                ('not_ready_time', models.IntegerField(default=0, verbose_name='not ready time')),
                ('wait_time', models.IntegerField(default=0, verbose_name='not ready time')),
                ('managed', models.IntegerField(default=0, verbose_name='managed')),
                ('is_total', models.BooleanField(default=False, verbose_name='is total?')),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='analytics.performance', verbose_name='performance')),
            ],
            options={
                'verbose_name': 'performance row',
                'verbose_name_plural': 'performance rows',
                'db_table': 'performance_rows',
            },
        ),
    ]
